### ISSUE TITLE
有一个小问题

### ISSUE THREAD

**Issue by baisesecxxx** [iiiusky/AntiHoneypot-Chrome-simple#2]
写好匹配规则后，访问蜜罐，第一次无缓存情况下，不会弹出蜜罐提示框，js文件已加载，信息被蜜罐捕捉，再次F5刷新才会提示蜜罐脚本屏蔽

**Comment by iiiusky** [comment]
> 写好匹配规则后，访问蜜罐，第一次无缓存情况下，不会弹出蜜罐提示框，js文件已加载，信息被蜜罐捕捉，再次F5刷新才会提示蜜罐脚本屏蔽

你试试调试一下这个插件的背景页，看一下是否加载到判断的过程。

**Comment by baisesecxxx** [comment]
第一次访问根本没有判断

**Comment by iiiusky** [comment]
> 第一次访问根本没有判断

问题已修复，因为js异步请求的问题
